### ISSUE TITLE
CHScrobbler doesn't support nordic characters

### ISSUE THREAD

**Issue by Kuhnus** [angelolz/CHScrobbler#34]
Program currently fails to authenticate if password includes at least any of the characters "äö".
Changing password to remove those characters resulted in successful login, but this should be fixed at some point since Last.FM itself supports such letters to be used and those are very commonly used in nordic countries.

Also a separate issue, the program currently terminates immediately if it cannot connect to the internet so could there be added for a notification to user about it before closing?

Otherwise, wonderful idea to see such scrobbler being built for Clone Hero too, thanks for that!

**Comment by angelolz** [comment]
Thanks for the issue report! I never thought about these characters. I assumed Java would handle them, but I guess it would need to be read in a different encoding.

I could definitely add a warning for no internet connection before closing. Good suggestion!

Thank you very much for using CHScrobbler :)

**Comment by angelolz** [comment]
The fix was a lot easier than I expected! The fix will be pushed in the next version. I'll keep this issue open until then. Thanks!

**Comment by angelolz** [comment]
Just made an update to CHScrobbler with this fix included. Please try it out and let me know if it works out for you :) If you experience any issues, please feel free to reopen this issue!
