### ISSUE TITLE
Error when selection scorespy

### ISSUE THREAD

**Issue by Insan3e** [angelolz/CHScrobbler#35]
![Screenshot 2024-01-13 023459](https://github.com/angelolz/CHScrobbler/assets/68969222/5561b878-37ad-4ddd-8949-e4abab1324b0)
I get this error after I select scorespy, I have java installed and an currentsong.txt is there so I'm not sure what the issue could be.

**Comment by maciejek052** [comment]
I also had this error when I was using JDK 8, when I updated to JDK 21 it worked.

**Comment by Insan3e** [comment]
Oh thank you! Updating to JDK 21 worked for me as well!

**Comment by Insan3e** [comment]
Oh thank you! Updating to JDK 21 worked for me as well!
